export const PERFORMANCE: string = "performance"
export const SNAPSHOT: string = "snapshot"
export const IOPS_GRAPH = "IOPS_GRAPH"
export const THROUGHPUT_GRAPH = "THROUGHPUT_GRAPH"
export const DATE = "date"
export const HOURS = "hours"
export const MINUTES = "minutes"